### ISSUE TITLE
Replace 'Proxy' name to avoid interference with Proxy keyword

### ISSUE THREAD

**Issue by hugozap** [hugozap/react-samy-svg#1]

**Comment by lifeiscontent** [comment]
@hugozap what do you think of calling it "Inject"?

**Comment by lifeiscontent** [comment]
I'd also recommend renaming select to selector

**Comment by lifeiscontent** [comment]
@hugozap can I get an update? I'd like to use this library, but this issue is a non-starter for me.

**Comment by hugozap** [comment]
@lifeiscontent I just published a new version (2.0.0) with the following changes:
- renamed select to selector
- renamed Proxy to SvgProxy

**Comment by lifeiscontent** [comment]
@hugozap, I guess that’s fine. I wish you would of had a discussion about it but I guess it’s your library so whatever.

**Comment by hugozap** [comment]
I did consider your suggestions but in my opinion proxy is closer to the intent of updating the element through an intermediary (Although I think "Mutate" also works and may be even more intuitive).  For now avoiding the Proxy keyword was the critical issue. If the name 'SvgProxy' causes confusion I'll definitely change it ( or add another named export ).
