### ISSUE TITLE
update

### ISSUE THREAD

**Issue by lifeiscontent** [hugozap/react-samy-svg#14]
Hey @hugozap ,

not sure if this fits your usecase, but I realized rather than having all these external dependencies, I should just use `svgr` to create a bunch of react components and then do the mutations in react like `react-samy-svg` does. If you want to check it out, here's the code: https://github.com/lifeiscontent/react-mutate-icon

**Comment by hugozap** [comment]
That's nice, one of my motivations was having the ability to work with remote random svgs. Very useful for demos/training. A minimal demo can be created really quickly https://codesandbox.io/s/km4mvqm3xv
Thanks for sharing!

**Comment by lifeiscontent** [comment]
@hugozap no worries man ;)
