### ISSUE TITLE
Do you know of a way to detect when the SVG has fully rendered?

### ISSUE THREAD

**Issue by brandondurham** [hugozap/react-samy-svg#15]
I’m having an issue with animating my large SVG in. It’s just a simple fade, but the actual render happens so late in the fade that it’s impossible to see.

Any suggestions?

**Comment by hugozap** [comment]
Hi, you can use the onSVGReady callback prop and trigger your animation
from there.
onSVGReady is called when the svg has been loaded and injected.

**Comment by hugozap** [comment]
Something like
` <Samy
        path="1.svg"
        onSVGReady={svg => {
          //trigger animation from here, changing state or manipulating the svg node directly

        }}
      />`

**Comment by brandondurham** [comment]
Sheesh. Didn’t even see that. Thank you!
