### ISSUE TITLE
Why all of the extra <div /> wrappers?

### ISSUE THREAD

**Issue by brandondurham** [hugozap/react-samy-svg#16]
Talking about this output:

![image](https://user-images.githubusercontent.com/250210/33904086-79a899a6-df48-11e7-8ed3-f294cec01137.png)

I’m a stickler for elements with no decoration (classes, styles, etc.) hanging around in the DOM. Three `<div />` tags wrapping the SVG is making me cringe. Any way to condense or remove these?

**Comment by hugozap** [comment]
Hi. I think this can be done with the new support for fragments in react v16.
I think that one of those divs is added by the library used to inject the SVG, the other is by samy and can't remember where the other comes from.

Its on my TODO list but if someone wants to jump to it, that would be great.

**Comment by hugozap** [comment]
Fixed in v3.0.0.  Wrapper divs are not required anymore thanks to React.Fragment api (requires React v16.2.0+)
