### ISSUE TITLE
Current master seems broken. Error with prop types on dependency react-svg

### ISSUE THREAD

**Issue by hugozap** [hugozap/react-samy-svg#18]
Getting the following error:
`TypeError: Cannot read property 'func' of undefined`
node_modules/react-svg/lib/index.js:116
`callback: _react.PropTypes.func,`

Probably related to updating dependencies in recent commits. @tokyoincode Maybe the react / react-dom version required for fragments doesn't work with the react-svg dependency? ( Tests run ok but examples don't ).

**Comment by tokyoincode** [comment]
Might be it, will check it out.

**Comment by tokyoincode** [comment]
[Looks like they haven't updated react in a while](https://github.com/atomic-app/react-svg/blob/master/package.json#L42-L43)

**Comment by hugozap** [comment]
The problem is with proptypes. Maybe forking their project to update it. Not sure if their dependency (SVG injector ) also needs to be updated. Have any ideas?

**Comment by tokyoincode** [comment]
Yeah, I was looking into replacing  or writing our own `react-svg`; I wonder how much work that would take though.

**Comment by tokyoincode** [comment]
Updating it would work as well.

**Comment by tokyoincode** [comment]
> Yeah, I was looking into replacing or writing our own react-svg;
☝️  Will be looking into this during my break (and after work)

**Comment by hugozap** [comment]
If react-svg breaks for latest version of react then maybe opening an issue
there will be enough if they are interested in fixing it. (Maybe someone
else already opened one as this basically breaks that lib)

El 19 dic. 2017 12:52 PM, "tokyoincode" <notifications@github.com> escribió:

Yeah, I was looking into replacing or writing our own react-svg;
☝️ Will be looking into this during my break (and after work)

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/hugozap/react-samy-svg/issues/18#issuecomment-352632491>,
or mute the thread
