### ISSUE TITLE
Warning: setState(...): Can only update a mounted or mounting component.

### ISSUE THREAD

**Issue by brandondurham** [hugozap/react-samy-svg#21]
Getting this error:

```
warning.js?6327:33 Warning: setState(...): Can only update a mounted or mounting component.
This usually means you called setState() on an unmounted component. This is a no-op.
Please check the code for the Samy component.
```

I can post code but wanted to know if you’d seen this before first…

**Comment by hugozap** [comment]
I've seen that error when working with timers but it can happen on any async call. A snippet would be useful to investigate.

By the way, I'm close to publish a big refactor so its possible the issue will be solved (if related to Samy). One of the biggest improvements is removing the extra request needed to load the SVG file when using the svgXml so you can use:

`<Samy svgXML={svgContents} width="300px" height="200px">
             <SvgProxy selector="#Group" fill={this.props.color}/>
             <SvgProxy selector="#Rectangle polygon" transform={tr}/>
   </Samy>
`
Here, no 'path' property is used, the svgXML prop receives the svg contents. If you use webpack you can use the raw-loader and when you import the asset its contents will be read. ( or rename just svg to something like mygraphic.svg.txt so the raw-loader gets used )

You can give it a try now by updating the dependency in package.json and re installing it:
"hugozap/react-samy-svg#refactor"

( `path` prop is still supported and will trigger the ajax loading of the svg file, but that's only recommended if you are loading the asset from a external domain }

- Another issue solved is the extra <div> wrappers. React Fragments were used so you need a recent React version.

**Comment by hugozap** [comment]
I'm looking into it, one question, if you use a hardcoded url as prop path, do you get the same error?  (with the current master or the new build). 

One scenario where the error could appear is when the component is removed before the svg gets loaded. Not sure if that could be the case.

**Comment by hugozap** [comment]
Another thing to keep in mind (for the new build) is that React version should be 16.2+ to support Fragments.

**Comment by hugozap** [comment]
Latest version accounts for the case when the svg is loaded but the component has been unmounted. I'll be closing this for now, but feel free to re open if you are still having issues.
