### ISSUE TITLE
doesn't render properly.

### ISSUE THREAD

**Issue by edwinlimlx** [hugozap/react-samy-svg#22]
Hi, 
Thanks for the great plugin, however encounter some issues, hope that you can help.

I have the following code:
```
<Samy path={menuIcon} style={{ width: '1em', height: '1em' }}>
  <SvgProxy selector="#icon" fill="currentColour"></SvgProxy>
</Samy>
```

However it render out to be: 
```
<svg data-src="http://localhost:8080/local-filesystem/xxx/icon.svg" src="" style="width: 1em; height: 1em;"></svg>
```

Which does not load the icon. 

react-dom/react: 16.2.0
react-samy-svg: 3.0.0
wkwebview

Pretty sure the file exist, as if I change it to </img> it works. however i need to access the fill attribute, thus the usage of this plugin.

**Comment by hugozap** [comment]
Can you test opening the page from a browser different than wkwebview?
It looks like the ajax request is failing for some reason.
When using the path attribute the same ajax restrictions apply (same origin restrictions unless the server has CORS enabled).

You can try with a public url: https://raw.githubusercontent.com/hugozap/react-samy-svg/master/examples/1.svg

(If you change the path to that, does it work? )

**Comment by hugozap** [comment]
I'm not sure if you are serving the react app from a server or the file system. If its the latter ajax requests cannot load file system resources, In that case you can load the contents of the file and use the Samy svgXML attribute instead of path.

**Comment by edwinlimlx** [comment]
Hi @hugozap Thanks for getting back! You might be leading in the right direction. I'm doing a cordova + react build, using wkwebview + [wkwebview-engine-localhost](https://github.com/apache/cordova-plugins/tree/wkwebview-engine-localhost) + [cordova-plugin-wkwebview-file-xhr](https://github.com/oracle/cordova-plugin-wkwebview-file-xhr)

I've no problem loading local persistent assets after using the xhr plugin. Persistent files now resides in the http://localhost:8080/local-filesystem path. 

The https://raw.githubusercontent.com/hugozap/react-samy-svg/master/examples/1.svg renders and loads well. Seems like some initialisation issues?

I've tried using <img src={menuIcon} /> loads fine like the other assets too

**Comment by hugozap** [comment]
Is it possible to load the asset dynamically with the xhr plugin and then passing the contents to Samy via svgXML?

**Comment by hugozap** [comment]
I'm not familiar with cordova but if you can request the asset via ajax or xhr plugin and store the value in the react component state then you could do: 
`{ this.state.svgContents && <Samy svgXML={ this.state.svgContents } > .... </Samy> }`

**Comment by edwinlimlx** [comment]
I've added additional attribute to the access node in the cordova config. Hope this help other people out there. 
```<access allows-arbitrary-loads-for-media="true" allows-arbitrary-loads-in-web-content="true" allows-local-networking="true" origin="*" subdomains="true" />
```

Thanks @hugozap! you have been great help!

**Comment by hugozap** [comment]
I'm glad you solved it!

**Comment by hugozap** [comment]
hey @edwinlimlx I'm curious about projects built with this library (renamed to https://github.com/hugozap/react-svgmt) let me know if you have built anything interesting with it, thanks!
