### ISSUE TITLE
SVG with styled elements

### ISSUE THREAD

**Issue by justjuank** [hugozap/react-samy-svg#24]
Hi, I'm trying to use an svg that seems like it was exported generating <style>'s inside to set the svg element properties. When I try to use an <SvgProxy> it doesn't work because the <style>s have priority over the elements.

Is this supported by react-samy-svg? or should I try exporting it as a different format?

Thanks.

**Comment by hugozap** [comment]
What if you reset the <style> element contents with something like `<SvgProxy selector="style"> ...the new style contents ... </SvgProxy>` . I  think that may work as it will replace the style contents and give you the change to remove the rules you don't need.

**Comment by justjuank** [comment]
Oh awesome, I didn't know I could use the SvgProxy like that.
So it works but I have to take care of rewriting the whole style content like you said, so it loses the purpose of passing props to the SvgProxy. 
It would be cool if I could change properties in a specific style within <style> by passing props to the SvgProxy.
I may take a different approach, but it's nice to see that I can place content between the SvgProxy.
This is a very useful library.
Thanks!

**Comment by hugozap** [comment]
So far I haven't dealt with svgs that have inner style tags so haven't considered those cases. It opens some interesting possibilities though, I'll think about what useful patters can emerge from manipulating the inner style.

**Comment by hugozap** [comment]
Thinking about it, it would be useful to have some element similar to SvgProxy something like SvgStyle.
<SvgStyle> 
  circle : {
    stroke: '#fff';
 }
</SvgStyle>

it would allow overriding styles. I see this being useful in different situations.

**Comment by justjuank** [comment]
Yeah that would be very useful, although I don't think React would let you use that syntax. When I used the <SvgProxy> to replace the <style> content I had to pass it as a string like:
`<SvgProxy selector="style">{'circle:{ fill: #000000;}'}</SvgProxy>`

**Comment by justjuank** [comment]
Another thing I noticed using the selector="style" is that if you use CSS classes in one <Samy> component it could affect other SVGs that use the same CSS class, example:

```
            <Samy path={MySVG}>
              <SvgProxy selector="#MyLayer path, #MyLayer polygon" fill="#FFFFFF"/>
            </Samy>
            <Samy path={AnotherSVG}>
              <SvgProxy selector="style">{`
                .st0{fill:#685651;}
                .st1{fill:#4C3B3D;}`}
              </SvgProxy>
            </Samy>
```

If MySVG has the same css classes applied in its elements it will be affected by the second one.

**Comment by hugozap** [comment]
What you can do is add a class to the parent Samy element 
`
<Samy className="mysvg" path={AnotherSVG}>
              <SvgProxy selector="style">{`
                .mysvg .st0{fill:#685651;}
                .mysvg .st1{fill:#4C3B3D;}`}
              </SvgProxy>
            </Samy>
`
Haven't try it but I think it should work.

**Comment by justjuank** [comment]
Ah yeah, a wrapper for the styles would work thanks!
Do you know if it's possible to nest <Samy> objects within <SvgProxy>? I'm trying to replace the content of a layer with another <Samy> svg but nothing happens.
I'm doing it like this:

```
<Samy path={CharacterBase} >
	 <SvgProxy selector="#Hair">
	          <Samy path={CharacterHair}>
	          </Samy>
	 </SvgProxy>
</Samy>
```

I'm trying to have a modular character built by different SVGs. Also, sorry for the bunch of questions.

**Comment by hugozap** [comment]
No worries about questions, they are very useful to discover new patterns for next versions.

SvgProxy contents are expected to be string (not a React element) and they are assigned to the SVG node using textContent so that's not going to work. They were designed to replace text nodes (text, tspan).

For your use case, (injecting one svg into another) I don't think that's possible right now, sadly injecting SVG is not as easy as HTML (there's no innerHTML equivalent for SVG). That would be very handy to have.

Right now, the recommended approach is to have everything on the same SVG file. If you need something more complex then you'll have to manually update the SVG node (by using the `onElementSelected` prop)
