### ISSUE TITLE
"OnElementSelected" is not called

### ISSUE THREAD

**Issue by musatarosu335** [hugozap/react-samy-svg#26]
Thank you for a great tool.
I have one question.

I ran the following code.
(`template` contains the path to the SVG file)
```jsx
const SvgComponent = ({ template }) => (
  <Samy path={template}>
    <SvgProxy
      selector="#Image image"
      onElementSelected={e => (console.log(e))}
    />
  </Samy>
);
```
In the first rendering,
```js
onElementSelected = {e => (console.log (e))}
```
Although the contents of it are displayed,
After the second time (`template` contents change and re-rendered)` onElementSelected` will not be called.

Why'onElementSelected` is not called?

Thank you.

**Comment by hugozap** [comment]
Thanks for the report.  I just fixed this issue in the new repository [https://github.com/hugozap/react-svgmt](https://github.com/hugozap/react-svgmt) Please change your dependency to react-svgmt and change Samy to SvgLoader.

**Comment by musatarosu335** [comment]
Thank you for fixing ：）
