### ISSUE TITLE
using passthrough props instead of svgAttributes

### ISSUE THREAD

**Issue by lifeiscontent** [hugozap/react-samy-svg#9]
@hugozap I realized, you already do this with `SvgProxy`, instead of having a seperate svgAttributes why don't we just pass all the props except the ones that are custom?

e.g.

```jsx
<Samy path="my.svg" width="40px" height="40px" />
```

vs

```jsx
<Samy path="my.svg" svgAttributes={{width: '40px', height:'40px'}} />
```

**Comment by hugozap** [comment]
Yeah, the reason is there's a few wrapper divs before the svg node, so there has to be a way to target the wrapper and another to target the svg node. 

Ideally only the svg node would be rendered, but I did not find a way to do that, not sure if with react 16 we can.

**Comment by lifeiscontent** [comment]
@hugozap I'll do some experimentation tonight and see if I can get it working. I'll send a PR if I can pull it off.

**Comment by hugozap** [comment]
@lifeiscontent I think this comes just in time https://reactjs.org/blog/2017/11/28/react-v16.2.0-fragment-support.html
That would remove the main div, the other is added by the svg loader library.

**Comment by lifeiscontent** [comment]
@hugozap you can see my WIP here: https://github.com/lifeiscontent/react-svg-injector

One thing I noticed about the proxy object and the code you wrote is when you add an event listener such as onClick to a proxy it doesn't map 1 to 1 to the props correctly, since react uses synthetic events the prop onClick won't work but onclick will work. Any ideas on how to solve for this issue? I spent some time last night reading the source of ReactDOM but didn't seem to find anything significant that explained how the translation worked.

Let me know if you have any ideas on this subject.

**Comment by lifeiscontent** [comment]
Fixed!
